#!/usr/bin/env node

/**
 * generate-latex.mjs — Validate and compile a generated .tex CV file to PDF
 *
 * Usage:
 *   node generate-latex.mjs <input.tex> [output.pdf]
 *
 * Reads the .tex file, validates structure, compiles to PDF via pdflatex.
 * If output.pdf is omitted, writes to the same directory as input with .pdf extension.
 * The .tex file is generated by the AI agent using templates/cv-template.tex.
 *
 * Requires: pdflatex (MiKTeX or TeX Live) on PATH.
 */

import { readFile, stat, copyFile, rm } from 'fs/promises';
import { resolve, basename, dirname, join } from 'path';
import { execFileSync } from 'child_process';
import { existsSync, mkdirSync } from 'fs';

// Each group represents one required section; any one pattern in the group is sufficient.
// Patterns cover: English, German (DE), French (FR), Portuguese (PT), Russian (RU), Japanese (JA).
const REQUIRED_SECTION_GROUPS = [
  {
    label: 'Education',
    patterns: [
      /\\section\{Education\}/, /\\section\{Ausbildung\}/, /\\section\{Bildung\}/,
      /\\section\{Formation\}/, /\\section\{Educa[çc]ão\}/, /\\section\{Обр/,
      /\\section\{学歴\}/,
    ],
  },
  {
    label: 'Experience',
    patterns: [
      /\\section\{Work Experience\}/, /\\section\{Experience\}/,
      /\\section\{Berufserfahrung\}/, /\\section\{Erfahrung\}/,
      /\\section\{Exp[ée]rience/, /\\section\{Experi[eê]ncia\}/, /\\section\{Опыт/, /\\section\{職務/,
    ],
  },
  {
    label: 'Projects',
    patterns: [
      /\\section\{Personal Projects\}/, /\\section\{Projects\}/,
      /\\section\{Projekte\}/, /\\section\{Projets\}/,
      /\\section\{Projetos\}/, /\\section\{Проекты\}/, /\\section\{プロジェクト\}/,
    ],
  },
  {
    label: 'Skills',
    patterns: [
      /\\section\{Technical Skills\}/, /\\section\{Skills\}/,
      /\\section\{Technische Kenntnisse\}/, /\\section\{Kenntnisse\}/,
      /\\section\{Comp[ée]tences/, /\\section\{Habilidades\}/,
      /\\section\{Навыки\}/, /\\section\{スキル\}/,
    ],
  },
];

const REQUIRED_COMMANDS = [
  '\\\\resumeSubheading',
  '\\\\resumeItem',
  '\\\\resumeProjectHeading',
];

async function main() {
  const inputPath = process.argv[2];
  const outputPath = process.argv[3]; // optional
  if (!inputPath) {
    console.error('Usage: node generate-latex.mjs <input.tex> [output.pdf]');
    process.exit(1);
  }

  const absPath = resolve(inputPath);
  let content;
  try {
    content = await readFile(absPath, 'utf-8');
  } catch (err) {
    console.error(`Error reading ${absPath}: ${err.message}`);
    process.exit(1);
  }

  const issues = [];

  // Check required sections (multilingual: any one pattern per group is sufficient)
  for (const group of REQUIRED_SECTION_GROUPS) {
    const found = group.patterns.some(pattern => pattern.test(content));
    if (!found) {
      issues.push(`Missing ${group.label} section (checked EN/DE/FR/PT/RU/JA variants)`);
    }
  }

  // Check required commands are used
  for (const cmd of REQUIRED_COMMANDS) {
    if (!new RegExp(cmd).test(content)) {
      issues.push(`Missing command: ${cmd}`);
    }
  }

  // Check document structure
  if (!content.includes('\\begin{document}')) {
    issues.push('Missing \\begin{document}');
  }
  if (!content.includes('\\end{document}')) {
    issues.push('Missing \\end{document}');
  }

  // Check for unresolved placeholders
  const unresolvedMatch = content.match(/\{\{[A-Z_]+\}\}/g);
  if (unresolvedMatch) {
    issues.push(`Unresolved placeholders: ${[...new Set(unresolvedMatch)].join(', ')}`);
  }

  // Check for common unescaped special chars in text (heuristic)
  const lines = content.split('\n');
  let resumeItemCount = 0;
  let subheadingCount = 0;
  let projectHeadingCount = 0;

  for (const line of lines) {
    if (/\\resumeItem\{/.test(line)) resumeItemCount++;
    if (/\\resumeSubheading[^C]/.test(line)) subheadingCount++;
    if (/\\resumeProjectHeading/.test(line)) projectHeadingCount++;
  }

  // Check pdfgentounicode
  if (!content.includes('\\pdfgentounicode=1')) {
    issues.push('Missing \\pdfgentounicode=1 (ATS compatibility)');
  }

  const fileInfo = await stat(absPath);
  const sizeKB = (fileInfo.size / 1024).toFixed(1);

  // Output report as JSON
  const report = {
    file: basename(absPath),
    path: absPath,
    sizeKB: parseFloat(sizeKB),
    counts: {
      resumeItems: resumeItemCount,
      subheadings: subheadingCount,
      projectHeadings: projectHeadingCount,
    },
    issues,
    valid: issues.length === 0,
  };

  // If validation fails, report and exit
  if (issues.length > 0) {
    console.log(JSON.stringify(report, null, 2));
    process.exit(1);
  }

  // --- Compile .tex → .pdf via pdflatex ---
  const texDir = dirname(absPath);
  const texBase = basename(absPath, '.tex');
  const defaultPdf = join(texDir, `${texBase}.pdf`);
  const targetPdf = outputPath ? resolve(outputPath) : defaultPdf;

  // Ensure output directory exists
  const targetDir = dirname(targetPdf);
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  try {
    // Run pdflatex twice for cross-references (standard practice)
    const pdflatexArgs = [
      '-no-shell-escape',
      '-interaction=nonstopmode',
      '-halt-on-error',
      `-output-directory=${texDir}`,
      absPath,
    ];

    // First pass
    execFileSync('pdflatex', pdflatexArgs, {
      cwd: texDir,
      stdio: 'pipe',
      timeout: 120_000,
    });

    // Second pass (resolves references)
    execFileSync('pdflatex', pdflatexArgs, {
      cwd: texDir,
      stdio: 'pipe',
      timeout: 120_000,
    });

    report.compiled = true;
  } catch (err) {
    // Try to extract useful error from pdflatex log
    const logPath = join(texDir, `${texBase}.log`);
    let latexError = err.message;
    try {
      const log = await readFile(logPath, 'utf-8');
      const errorLines = log.split('\n').filter(l => l.startsWith('!'));
      if (errorLines.length > 0) {
        latexError = errorLines.join('\n');
      }
    } catch { /* no log file */ }

    report.compiled = false;
    report.compileError = latexError;
  }

  // Post-compile: move PDF and clean up (separate from compile errors)
  if (report.compiled) {
    try {
      // Move PDF to target location if different
      if (resolve(defaultPdf) !== resolve(targetPdf)) {
        await copyFile(defaultPdf, targetPdf);
        await rm(defaultPdf).catch(() => {});
      }

      const pdfStat = await stat(targetPdf);
      report.pdf = {
        path: targetPdf,
        sizeKB: parseFloat((pdfStat.size / 1024).toFixed(1)),
      };
    } catch (err) {
      report.postCompileError = `Failed to finalize PDF: ${err.message}`;
    }

    // Clean up auxiliary files (best-effort)
    const auxExts = ['.aux', '.log', '.out', '.fls', '.fdb_latexmk', '.synctex.gz'];
    for (const ext of auxExts) {
      await rm(join(texDir, `${texBase}${ext}`)).catch(() => {});
    }
  }

  console.log(JSON.stringify(report, null, 2));
  process.exit(report.compiled ? 0 : 1);
}

main();
